### ISSUE TITLE
string index out of range at self.msg_zero2=rest[0]

### ISSUE THREAD

**Issue by schneider42** [muccc/iridium-toolkit#14]
```
Traceback (most recent call last):
  File "../iridium-toolkit/iridium-parser.py", line 1233, in <module>
    do_input(input)
  File "../iridium-toolkit/iridium-parser.py", line 1177, in do_input
    perline(Message(line.strip()).upgrade())
  File "../iridium-toolkit/iridium-parser.py", line 160, in upgrade
    return IridiumMessage(self).upgrade()
  File "../iridium-toolkit/iridium-parser.py", line 404, in upgrade
    return IridiumECCMessage(self).upgrade()
  File "../iridium-toolkit/iridium-parser.py", line 612, in upgrade
    return IridiumMSMessage(self).upgrade()
  File "../iridium-toolkit/iridium-parser.py", line 986, in upgrade
    return IridiumMessagingAscii(self).upgrade()
  File "../iridium-toolkit/iridium-parser.py", line 1042, in __init__
    self.msg_zero2=rest[0]
IndexError: string index out of range
```

**Comment by Sec42** [comment]
I'm pretty sure this doesn't happen anymore in current iridium-parser. Please let me know if you're able to reproduce this.
